label daytwo:
    "I sit in my living room watching a random TV show."
    mc "Damn, Japanese game shows are a lot weirder that I remember."
    "It's 10:47 AM. Natsuki send me a text and told me she'll be here soon."
    "I'm really nervous."
    "As I'm about to get lost in my nervousness, I hear the doorbell ring."
    "That must be Natsuki."
    "I make my over and open the door."
    show natsuki 1bl at t11
    n "Hey! What's up?"
    mc "Uh... Hi!"
    "I've never seen Natsuki without her uniform."
    "She's... {i}actually pretty hot{/i} in her casual clothes!"
    n 1bb "Um, Hello? Earth to [player]?"
    "Oh! I'm sorry, plase come in."
    show natsuki 1ba
    "I let Natsuki inside and close the door behind us."
    n 4bd "So, ready to read?"
    mc "Sure! There's not much room on the livingroom table, so we could use the desk upstairs."
    n "After you!"
    show natsuki at thide
    hide natsuki
    scene bg bedroom
    with wipeleft
    "Natsuki and I make our way upstairs and into my room."
    show natsuki 1ba at t11
    mc "You can take a seat at my desk if you want."
    n 1bd "Actually, I think I'd prefer we sit on the floor."
    mc "Really?"
    n "Yeah, that's how I like to read at home."
    mc "Alright then. Take a seat."
    mc "Oh and by the way, how long is your father letting you stay?"
    n 4bc "Surprisingly he said he wouldn't mind if I stayed until late."
    n "So I guess that means before midnight."
    n 1bd "So we'll have plenty of time to read!"
    show natsuki 1ba
    "Natsuki unzips her bag and pulls out the first chapter of Parfait Girls."
    n 1bd "Let's get to it then."
    show natsuki at thide
    hide natsuki
    "Natuski and I take a seat on the floor."
    "Natuski inches a lot closer to me and opens the manga."
    "We begin to read the first two pages in silence."
    n "You just tell me when to turn the page, ok?"
    mc "Yup."
    "This artstyle is very saturated and flashy, like you'd expect from a magical girl manga."
    "The dialogue is a bit cheesy, but it works."
    scene bg bedroom_night
    with wipeleft_scene
    stop music fadeout 2.0
    "We're down to the 10th chapter of Parfait Girls."
    "By now it's already gotten dark outside, though it's only 8 o'clock."
    mc "I have to admin, this book is not that bad."
    n "I knew you'd like it!"
    mc "You can turn the page now."
    n "Alrightyy~"
    "Natsuki licks her finger like a boomer and turns the page."
    "..."
    n "O-Oh... I'm sorry, I forgot about this part."
    "The next pages of the manga aren't safe for work."
    "Natsuki didn't tell me this manga was R18."
    mc "It's alright, I don't mind it."
    "We awkwardly keep reading."
    n "They sure look like they're having fun."
    mc "Yeah..."
    "I fell Natsuki inch even closer to me."
    "By now I can feel hear breath on my neck."
    "Before long, Natsuki rests her head on my shoulder."
    "My heart begins to race."
    "Without me even asking, Natsuki turns the page."
    "The scene becomes even more intense."
    "I notice Natsuki start breathing heavier and heavier, as I begin to do the same."
    "Natsuki turns the page once again."
    "At this point I bet she doesn't even care about dialogue, she just wants to see the action."
    "Her turning the page once more confirms that."
    "Unfortunately for Natsuki, the scene ends on the following page."
    "She's clearly disappointed."
    n "You know, reading this was fun, but now it's getting a bit boring."
    n "Don't you want to do... something else?"
    mc "Like what?"
    n "Ugh! {i}Think,{/i} dumbass!"
    "..."
    mc "Oh, my bad."
    "I snatch the book out of Natsuki's hand and throw it on the bed."
    "I grab Natsuki by her waist and push her on her back, as I lay on top of her."
    "She doesn't protest."
    scene black
    with wipeleft
    "Without wasting a second, I close my eyes and move my head forward and touch lips with her, and we start making out."
    "She wraps her hands around me."
    "We make out very intensely, for what felt like at least half an our, before we part lips."
    n "I didn't expect you to be this good at this, you know?"
    mc "I'll take that as a compliment."
    "Natsuki and I stand up, but before I can catch my breath, Natsuki leans in and we start making out again."
    "I put my hands under Natsuki's shirt, touching her bare skin and undoing her bra."
    "I grab her shirt and lift it up."
    "Our lips part for a second, to allow Natsuki's shirt to go over her head, before throwing it on the floor and getting right back at it."
    "Natsuki takes off her already undone bra and presses her chest against mine."
    "I place my hand on Natsuki's and caressing her collarbone."
    "She lets out soft moans, wich do nothing but arouse me even more."
    "Suddenly, Natsuki pushes me on my back, changing our position to be opposite of the one we were in before, with Natuski on top."
    "We start making out even more intensely."
    "My hand automatically places itself on Natsuki ass."
    "I pull her skirt down, and Natsuki discards it on the floor, spreading her legs."
    "Suddenlty, Natsuki pulls her lips apart from mine and gets up."
    "Still on the floor, I open my eyes."
    scene black
    show rick
    $ renpy.pause(1, hard=True)
    scene bg bedroom_night
    show natsuki 6a at t11
    mc "Is everthing alright, Natsuki?"
    n "Yeah, but you know..."
    n "The floor isn't really that comfortable, so I thought we could use the bed."
    "I swiftly get up on my feet."
    mc "Yeah, you're right."
    "I step closer to Natsuki and place one hand on her hip and massage her breast with the other."
    n 6b "..."
    n "I know I'm not much to look at, but..."
    mc "You're beautiful just the way you are, Natsuki."
    n "..."
    n "Uuuuu~!"
    n "Just... Shut up and get on the bed, alright?"
    mc "As you wish..."
    show natsuki at thide
    hide natsuki
    "I forcefully push Natsuki on the bed and lay on top of her once again."
    "Before I can do anything, Natsuki grabs my shirt and pulls it off me, throwing it on the margin of the bed."
    "She then grabs me by my neck and pulls me into another deep kiss."
    "She then wraps her hands me and starts caressing my back up and down."
    "As my hands are free, I use them to spreat Natsuki legs."
    "I then place my hand in between them, and start gently rubbing her clitoris."
    n "Mmmh~"
    "As I do this, Natsuki starts moaning into my mouth, tightening her grip on my back."
    "I start going even faster."
    n "Hngggh~"
    "She's definitely enjoying this, so it's time to take it a bit further."
    "I insert my middle finger inside Natsuki, and start massaging the inside of her vagina."
    n "M-Mmmmhh!~"
    n "Mmmm!"
    "She lets out even more moans, deeper than before."
    "I pull my lips away from Natsuki, and position my head in between her legs."
    n "W-wait!"
    "Nope."
    "As I move my finger even faster, I start licking Natsuki's clitoris."
    n "Kyaaaa~"
    n "A-Ahhhh!~"
    "I run circles around her clit with my tounge."
    "There's no denying she's enjoying the sensation."
    n "[player]! I-I'm~ c-cumming!"
    n "I'm... almost there!~"
    "Natsuki clenches her toes, as she moans even louder."
    n "Aaaaah~ f-fuck it feels so… good~"
    n "F-fuck! I-m... I'm cumming!"
    n "[player]!"
    n "Ahhhh!~"
    scene bg bedroom_night
    with flash
    n "Aaaaaaahh!~"
    n "Hngggggh~"
    n "Haaaaah~"
    n "Haaah~"
    "Natsuki struggles to catch hear breath."
    n "Holy fuck, that felt {i}amazing!{/i}"
    mc "I'm not done yet, you know?"
    n "H-huh?"
    mc "It's not fair for you to have all the fun~"
    n "Oh, I see. My bad."
    "Natsuki grabs the edge of my pants and begins taking them off."
    "As the pants reach my knees, she begins to rub the buldge on my underwear."
    "I feel myself get hard."
    "Natsuki finally pulls down my underwear, exposing my erect member."
    n "Uuuwah!"
    n "Y-You're huge, [player]!"
    "She wraps her lips around only the head of my penis, swirling her tounge around it."
    mc "Nnngh..."
    "Her mouth then slides to the base of my penis.."
    "I can feel hear hot breath on my stomach, as her tounge slides up and dowm."
    "Natsuki puts one hand on my balls, squeezing gently."
    "Her lips and tounge begin to press even harder against my dick."
    "Natsuki begins to move heer head faster."
    "Her mouth feels amazing~"
    "Natsuki gags, but keeps forcing herself."
    mc "Natsuki, t-this feels amazing~"
    "Natsuki responds by moving even faster."
    "I'm getting close to my limit."
    mc "I'm- almost there, Natsuki."
    "I can't help but grab Natsuki by her head, pulling her hair to thrust myself into her mouth."
    "I giver her three hard, deep thrusts, as I bring myself to my limit."
    scene bg bedroom_night
    with flash
    n "Mmmh!"
    "Natsuki slides her mouth of my penis."
    "She swallows my semen while still rubbing my cock with her hand."
    n "So, did you like it?"
    mc "Yeah- That was amazing."
    "Natsuki leans back on the bed, and spreads her legs."
    "A smirk builds up on her face as she looks me in the eye."
    n "We both know we haven't had enough yet, right?"
    mc "Right."
    "I approach Natsuki, and position myself in between her legs."
    "I begin rubbing the head of my penis on the outside of Natsuki's vagina."
    n "Mmmh~"
    n "[player]... p-put in in, please."
    mc "With pleasure."
    "In one swift motion, I thrust myself inside Natsuki."
    n "A-Ahhhh!~"
    "I begin to move back and forth, with Natsuki moaning even louder with every thrust."
    n "Hngggh!~"
    n "Haaah~"
    n "Haaaaah!~"
    "As she moans, I feel Natsuki's insides tighten around me."
    mc "Natsuki, t-this feels great!"
    n "Y-yeah, I love it!~"
    "As I start to move my hips faster, I begin massaging her clitoris with my thumb."
    n "Kyaaaa!~"
    n "Wait! T-that's too much!"
    n "I dont think my body can take this much!~"
    n "Ahhhh!~"
    n "Haaaaah!~"
    n "It's- going all the way in!"
    "I don't stop moving."
    n "Hngggh!~"
    n "Haaah~"
    "I lay over Natsuki, and prass my lips against hers."
    "We start kissing, as the ocasionally moans into my mouth."
    "I can feel that another orgasm is close."
    n "Hngggggh!~"
    n "Mmmmmh!"
    "I thrust myself into Natsuki even harder."
    "She moans uncontrollably, signaling she's close too."
    n "M-Mmmmhh!~"
    scene bg bedroom_night
    with flash
    n "Aaaaaaahh!~"
    n "Haaaaah!~"
    n "Haaahh!~"
    n "Hngggggh, h-haaaaah!~"
    "As Natsuki finishes, I pull myself out of her."
    scene bg bedroom_night
    with flash
    mc "Hngggh!~"
    "As another orgasm hits me, I release another load on Natsuki's belly."
    "She catches her breath, and smiles at me."
    n "Jeez! Don't be so rough, [player]."
    n "I might get addicted, you know."
    "Natsuki and I giggle."
    mc "Sorry."
    n "You've made quite a mess, you know."
    n "Let's go take a shower, shall we?"
    mc "Yeah, that sounds good."
    scene bg bedroom_night
    with wipeleft_scene
    "Natsuki and I leave the bathroom, water still dripping from our naked bodies."
    show natsuki 6a at t11
    mc "Oh shit, I almost forgot. What time is it?"
    n "I don't know, why?"
    mc "Isn't your dad gonna get angry if you stay here until too late."
    n "..."
    "Natsuki is silent for a second, after witch she lets out a long, sad sigh."
    n "Look."
    n "My dad is not the strict and responsible parent you think he is."
    n "He's just a drunk loser who can't take care of himself, let alone his children."
    "I'm taken aback by Natsuki's words."
    n "So no, he won't get mad because he doesn't care."
    n "When I told him I was coming over to your house today, he didn't even say anything. He just nodded."
    n "So for all he cares I could be gone for good."
    mc "Natsuki, I-"
    mc "I's sorry, I didn't know it was like that."
    n "It's alright. I don't usually open up about it."
    mc "So, do you wanna sleep over this weekend?"
    mc "As you just saw, my bed is big enough for two."
    n "Yeah, that sounds like a good idea."
    show natsuki at thide
    hide natsuki
    with wipeleft
    "I get into bed, and Natsuki follows me."
    "She sits down with her body facing me, and rests her head on my chest."
    "I pull the sheets over bouth our bodies, and close my eyes."
    scene black
    with wipeleft
    mc "Good night, Natsuki."
    n "Good night, [player]."