label daytwo:
    "I sit in my living room watching a random TV show."
    mc "Damn, Japanese game shows are a lot weirder that I remember."
    "It's 10:47 AM. Natsuki send me a text and told me she'll be here soon."
    "I'm really nervous."
    "As I'm about to get lost in my nervousness, I hear the doorbell ring."
    "That must be Natsuki."
    "I make my over and open the door."
    show natsuki 1bl at t11
    n "Hey! What's up?"
    mc "Uh... Hi!"
    "I've never seen Natsuki without her uniform."
    "She's... {i}actually pretty hot{/i} in her casual clothes!"
    n 1bb "Um, Hello? Earth to [player]?"
    "Oh! I'm sorry, plase come in."
    show natsuki 1ba
    "I let Natsuki inside and close the door behind us."
    n 4bd "So, ready to read?"
    mc "Sure! There's not much room on the livingroom table, so we could use the desk upstairs."
    n "After you!"
    show natsuki at thide
    hide natsuki
    scene bg bedroom
    with wipeleft
    "Natsuki and I make our way upstairs and into my room."
    show natsuki 1ba at t11
    mc "You can take a seat at my desk if you want."
    n 1bd "Actually, I think I'd prefer we sit on the floor."
    mc "Really?"
    n "Yeah, that's how I like to read at home."
    mc "Alright then. Take a seat."
    mc "Oh and by the way, how long is your father letting you stay?"
    n 4bc "Surprisingly he said he wouldn't mind if I stayed until late."
    n "So I guess that means before midnight."
    n 1bd "So we'll have plenty of time to read!"
    show natsuki 1ba
    "Natsuki unzips her bag and pulls out the first chapter of Parfait Girls."
    n 1bd "Let's get to it then."
    show natsuki at thide
    hide natsuki
    "Natuski and I take a seat on the floor."
    "Natuski inches a lot closer to me and opens the manga."
    "We begin to read the first two pages in silence."
    n "You just tell me when to turn the page, ok?"
    mc "Yup."
    "This artstyle is very saturated and flashy, like you'd expect from a magical girl manga."
    "The dialogue is a bit cheesy, but it works."
    scene bg bedroom_night
    with wipeleft_scene
    stop music fadeout 2.0
    "We're down to the 10th chapter of Parfait Girls."
    "By now it's already gotten dark outside, though it's only 8 o'clock."
    mc "I have to admin, this book is not that bad."
    n "I knew you'd like it!"
    mc "You can turn the page now."
    n "Alrightyy~"
    "Natsuki licks her finger like a boomer and turns the page."
    "..."
    n "O-Oh... I'm sorry, I forgot about this part."
    "The next pages of the manga aren't safe for work."
    "Natsuki didn't tell me this manga was R18."
    mc "It's alright, I don't mind it."
    "We awkwardly keep reading."
    n "They sure look like they're having fun."
    mc "Yeah..."
    "I fell Natsuki inch even closer to me."
    "By now I can feel hear breath on my neck."
    "Before long, Natsuki rests her head on my shoulder."
    "My heart begins to race."
    "Without me even asking, Natsuki turns the page."
    "The scene becomes even more intense."
    "I notice Natsuki start breathing heavier and heavier, as I begin to do the same."
    "Natsuki turns the page once again."
    "At this point I bet she doesn't even care about dialogue, she just wants to see the action."
    "Her turning the page once more confirms that."
    "Unfortunately for Natsuki, the scene ends on the following page."
    "She's clearly disappointed."
    n "You know, reading this was fun, but now it's getting a bit boring."
    n "Don't you want to do... something else?"
    mc "Like what?"
    n "Ugh! {i}Think,{/i} dumbass!"
    "..."
    mc "Oh, my bad."
    "I snatch the book out of Natsuki's hand and throw it on the bed."
    "I grab Natsuki by her waist and push her on her back, as I lay on top of her."
    "She doesn't protest."
    scene black
    with wipeleft
    "Without wasting a second, I close my eyes and move my head forward and touch lips with her, and we start making out."
    "She wraps her hands around me."
    "We make out very intensely, for what felt like at least half an our, before we part lips."
    n "I didn't expect you to be this good at this, you know?"
    mc "I'll take that as a compliment."
    "Natsuki and I stand up, but before I can catch my breath, Natsuki leans in and we start making out again."
    "I put my hands under Natsuki's shirt, touching her bare skin and undoing her bra."
    "I grab her shirt and lift it up."
    "Our lips part for a second, to allow Natsuki's shirt to go over her head, before throwing it on the floor and getting right back at it."
    "Natsuki takes off her already undone bra and presses her chest against mine."
    "I place my hand on Natsuki's and caressing her collarbone."
    "She lets out soft moans, wich do nothing but arouse me even more."
    "Suddenly, Natsuki pushes me on my back, changing our position to be opposite of the one we were in before, with Natuski on top."
    "We start making out even more intensely."
    "My hand automatically places itself on Natsuki ass."
    "I pull her skirt down, and Natsuki discards it on the floor, spreading her legs."
    "Suddenlty, Natsuki pulls her lips apart from mine and gets up."
    "Still on the floor, I open my eyes."
    scene bg bedroom_night
    with wipeleft
    show natsuki 6a at t11
    mc "Is everthing alright, Natsuki."
    n "Yeah, but you know..."
    n "The floor isn't really that comfortable, so I thought we should use the bed."
    "I swiftly get up on my feet."
    mc "Yeah, you're right."
    "I step closer to Natsuki and place one hand on her hip and massage her breast with the other."
    n 6b "..."
    n "I know I'm not much to look at, but..."
    mc "You're beautiful just the way you are, Natsuki."
    n "..."
    n "Uuuuu~!"
    n "Just... Shut up and get on the bed, alright?"
    mc "As you wish..."
    show natsuki 6a
    "I forcefully push Natsuki on the bed and lay on top of her once again."
    "Before I can do anything, Natsuki grabs my shirt and pulls it off me, throwing it on the margin of the bed."
    "She then grabs me by my neck and pulls me into another deep kiss."
    show natsuki at thide
    hide natsuki 
    scene black
    with wipeleft
    "She then wraps her hands me and starts caressing my back up and down."
    "As my hands are free, I use them to spreat Natsuki legs."
    "I then place my hand in between them, and start gently rubbing her clitoris."
    n "Mmmh~"
    "As I do this, Natsuki starts moaning into my mouth, tightening her grip on my back."
    "I start going even faster."
    n "Hngggh~"
    "She's definitely enjoying this, so it's time to take it a bit further."
    "I insert my middle finger inside Natsuki, and start massaging the inside of her vagina."
    n "M-Mmmmhh!~"
    n "Mmmm!"
    "She lets out even more moans, deeper than before."
    "I pull my lips away from Natsuki, and position my head in between her legs."
    n "W-wait!"
    "Nope."
    "As I move my finger even faster, I start licking Natsuki's clitoris."
    n "Kyaaaa~"
    n "A-Ahhhh!~"
    "I run circles around her clit with my tounge."
    "There's no denying she's enjoying the sensation."
    n "[player]! I-I'm~ c-cumming!"
    n "I'm... almost there!~"
    "Natsuki clenches her toes, as she moans even louder."
    n "Aaaaah~ f-fuck it feels so… good~"
    n "F-fuck! I-m... I'm cumming!"
    n "[player]!"
    n "Ahhhh!~"
    "flash here"
    n "Aaaaaaahh!~"
    n "Hngggggh~"
    n "Haaaaah~"
    n "Haaah~"
    "Natsuki struggles to catch hear breath."
    n "Holy fuck, that felt {i}amazing!{/i}"
    mc "I'm not done yet, you know?"
    n "H-huh?"
    "I pull myself on top of Natsuki again, take my pants off."
    "Before long, I expose my erect member to Natsuki."
    "I begin rubbing the head of my penis on the outside of Natsuki's vagina."
    n "Mmmh~"
    n "[player]... p-put in in, please."
    mc "As you wish."
    "In one swift motion, I thrust myself inside Natsuki."
    n "A-Ahhhh!~"
    "I begin to move back and forth, with Natsuki moaning even louder with every thrust."
    n "Hngggh!~"
    n "Haaah~"
    n "Haaaaah!~"
    "As she moans, I feel Natsuki's insides tighten around me."
    mc "Natsuki, t-this feels amazing."
    n "I'm really glad!"
